# Code Generated by Sidekick is for learning and experimentation purposes only.
def unsafe_output(user_input):
    # This is an example of improper output encoding
    output = user_input
    return f"User input: {output}"

def safe_output(user_input):
    # This is an example of proper output encoding
    import html
    output = html.escape(user_input)
    return f"User input: {output}"
