name: Semgrep
 
on:
  push:
    branches: [main, master]
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/semgrep.yml'
      - '.semgrep/**'
 
jobs:
  semgrep:
    name: Run Semgrep Scan
    runs-on: ubuntu-latest
 
    permissions:
      contents: read
 
    container:
      image: returntocorp/semgrep
 
    steps:
      - uses: actions/checkout@v4
      - run: semgrep --config .semgrep --error
