name: Semgrep
 
on:
  push:
    branches: [main, master]
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/semgrep.yml'
      - '.semgrep/**'
 
jobs:
  semgrep:
    name: Run Semgrep Scan
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
 
      - uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep  # This points to the local rule directory
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}  # Optional: for dashboard integration
